### ISSUE TITLE
Unit test fixtures not found when integrating with cht-sync

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-pipeline#156]
**Describe the bug**
CHT Pipeline models are failing to build because the test fixtures for unit tests cannot be found.

**To Reproduce**

1. Set the `CHT_PIPELINE_BRANCH_URL` to "https://github.com/medic/cht-pipeline.git#main" or another repo that uses the main branch for the CHT Pipeline package.
2. Run dbt and see that models are not built successfully.

**Expected behavior**
All models are built successfully

**Logs**
```
2024-09-02 12:57:32 09:57:32  Encountered an error:
2024-09-02 12:57:32 Parsing Error
2024-09-02 12:57:32   File not found for fixture 'data_record_document_metadata_initial' in unit tests in models/forms/tests/forms.yml
2024-09-02 12:57:32 Traceback (most recent call last):
2024-09-02 12:57:32   File "/dbt/dbt-run.py", line 140, in <module>
2024-09-02 12:57:32     update_models()
2024-09-02 12:57:32   File "/dbt/dbt-run.py", line 117, in update_models
2024-09-02 12:57:32     manifest_json = get_manifest()
2024-09-02 12:57:32                     ^^^^^^^^^^^^^^
2024-09-02 12:57:32   File "/dbt/dbt-run.py", line 90, in get_manifest
2024-09-02 12:57:32     with open("/dbt/target/manifest.json", "r") as f:
2024-09-02 12:57:32          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-02 12:57:32 FileNotFoundError: [Errno 2] No such file or directory: '/dbt/target/manifest.json'
```

**Additional context**
I tried adding a [test-paths](https://docs.getdbt.com/reference/project-configs/test-paths) entry and set it to `test` but that did not work. I also tried renaming the `test` folder to `tests` but that did not work either

**Comment by lorerod** [comment]
@njuguna-n as per [this](https://docs.getdbt.com/docs/build/unit-tests#when-to-run-unit-tests) recommendation we can ignore by _default_ the unit test in cht-sync. And, after we fix this we can make it configurable.
I tried including  `"--exclude", "test_type:unit"` flags in `cht-sync/dbt/dbt-run.py` but wasn't able to make it work.

**Comment by lorerod** [comment]
Also, the `test:e2e` command is not working when using `CHT_PIPELINE_BRANCH_URL="https://github.com/medic/cht-pipeline.git#main"`. I get:
```
Exception during run: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.join (node:path:1172:7)
    at file:///Users/marialorenarodriguezviruel/medic-workspace/cht-sync/tests/utils/postgres-utils.js:5:28
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async formattedImport (/Users/marialorenarodriguezviruel/medic-workspace/cht-sync/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async Object.exports.requireOrImport (/Users/marialorenarodriguezviruel/medic-workspace/cht-sync/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async Object.exports.loadFilesAsync (/Users/marialorenarodriguezviruel/medic-workspace/cht-sync/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/Users/marialorenarodriguezviruel/medic-workspace/cht-sync/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/marialorenarodriguezviruel/medic-workspace/cht-sync/node_modules/mocha/lib/cli/run.js:370:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by njuguna-n** [comment]
@lorerod I am looking into this as well. I have tried changing the command to `dbt build` instead of `dbt run` and adding the `--exclude-resource-type` flag but that didn't work either. Digging into it a bit more.

**Comment by lorerod** [comment]
@njuguna-n I also tried to use `DBT_EXCLUDE_RESOURCE_TYPES` env variables but for some reason is not working. The command that is failing is `dbt ls`
```
[0m14:35:03.433816 [error] [MainThread]: Encountered an error:
Parsing Error
  File not found for fixture 'document_metadata_initial' in unit tests in models/root/tests/document_metadata.yml
[0m14:35:03.435506 [debug] [MainThread]: Resource report: {"command_name": "list", "command_wall_clock_time": 3.977095, "process_user_time": 6.202093, "process_kernel_time": 0.191784, "process_mem_max_rss": "101320", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m14:35:03.437000 [debug] [MainThread]: Command `dbt ls` failed at 14:35:03.436751 after 3.98 seconds
[0m14:35:03.437477 [debug] [MainThread]: Flushing usage events
```

**Comment by lorerod** [comment]
Last thing I tried to include env in every call to dbt build or dbt ls. Like this: 
`subprocess.run(["dbt", "build",  "--profiles-dir", ".dbt", "--exclude", "config.materialized:view"],env=dict(os.environ, DBT_EXCLUDE_RESOURCE_TYPES='unit_test'))`
